# Generated by Django 4.2.11 on 2026-04-18 21:58

import EMS.models
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_code', models.CharField(default='None', max_length=7)),
                ('course', models.CharField(default='None', max_length=4)),
                ('semester', models.CharField(default='None', max_length=4)),
                ('branch', models.CharField(default='None', max_length=40)),
                ('subject', models.CharField(default='None', max_length=30)),
                ('paper', models.FileField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tusername', models.CharField(default='None', max_length=40)),
                ('s_code', models.CharField(default='None', max_length=7)),
                ('syllabus', models.FileField(default=None, upload_to='')),
                ('q_pattern', models.FileField(default=None, upload_to='')),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('enc_field', models.TextField(default='[]')),
                ('private_key', models.FileField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_code', models.CharField(max_length=7)),
                ('subject', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('teacher_id', models.CharField(blank=True, default=EMS.models.teacherID, max_length=20)),
                ('course', models.CharField(choices=[('None', 'None'), ('B.E.', 'B.E.'), ('M.E.', 'M.E.')], default='None', max_length=4)),
                ('semester', models.CharField(choices=[('None', 'None'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], default='None', max_length=4)),
                ('branch', models.CharField(choices=[('None', 'None'), ('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('BioTech', 'BioTech')], default='None', max_length=40)),
                ('subject', models.CharField(choices=[('None', 'None'), ('Compiler Design', 'Compiler Design'), ('Digital Signal Processing', 'Digital Signal Processing'), ('Cloud Computing', 'Cloud Computing'), ('Agile Development', 'Agile Development')], default='None', max_length=30)),
                ('role', models.CharField(choices=[('teacher', 'teacher'), ('coe', 'coe'), ('superintendent', 'superintendent')], default='teacher', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
